project_id = "uqtsrttzcrldkttkrxid"

[functions.invite-user]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.validate-qontak]
verify_jwt = false